server:
  port: 10012

spring:
  application:
    name: config-server
  cloud:
    config:
      profile: test
      #label: config-label-test
      #username: user
      #password: password
      #uri: http://localhost:${server.port}
      #discovery:
      #  enabled: true
      service-id: config-server
      server:
        git:
          uri:      # 配置git仓库的地址
          search-paths:                      # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:

# 服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka/